version: '3.8'

services:
  app:
    build: .
    hostname: backend-questions-ai
    container_name: backend-questions-ai
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      OPENAI_API_KEY: "token"
      TOKEN_HF: "token"
      PORT: 3000
    depends_on:
      - ollama
  ollama:
    build: 
      dockerfile: Dockerfile.Ollama
      context: .
    hostname: ollama
    container_name: ollama
    ports:
      - "11434:11434"
networks:
  app-ai:
    external: true